wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.18
    start_time: 1701529389.172966
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.8.18
      5: 0.13.5
      8:
      - 2
      - 5
batch_size:
  desc: null
  value: 4
epochs:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 1.0e-05
